services:
  env-substitution:
    environment:
      - OPENLMS_PUBLIC_URL=${OPENLMS_PUBLIC_URL}
      - OPENLMS_CLIENT_UUID=${OPENLMS_CLIENT_UUID}
      - OPENLMS_CLIENT_SECRET=${OPENLMS_CLIENT_SECRET}
      - KC_SMTP_HOST=${KC_SMTP_HOST}
      - KC_SMTP_PORT=${KC_SMTP_PORT}
      - KC_SMTP_FROM=${KC_SMTP_FROM}
      - KC_SMTP_FROM_DISPLAY_NAME=${KC_SMTP_FROM_DISPLAY_NAME}
      - KC_SMTP_TLS=${KC_SMTP_TLS}
      - KC_SMTP_SSL=${KC_SMTP_SSL}
      - KC_SMTP_AUTH=${KC_SMTP_AUTH}
      - KC_SMTP_REPLY_TO=${KC_SMTP_REPLY_TO}
      - KC_SMTP_REPLY_TO_DISPLAY_NAME=${KC_SMTP_REPLY_TO_DISPLAY_NAME}
