services:
  env-substitution:
    environment:
      - OPENLMS_PUBLIC_URL=${OPENLMS_PUBLIC_URL}
      - OPENLMS_CLIENT_UUID=${OPENLMS_CLIENT_UUID}
      - OPENLMS_CLIENT_SECRET=${OPENLMS_CLIENT_SECRET}
      - KC_SMTP_HOST=${KC_SMTP_HOST}
      - KC_SMTP_PORT=${KC_SMTP_PORT}
      - KC_SMTP_FROM=${KC_SMTP_FROM}
      - KC_SMTP_FROM_DISPLAY_NAME=${KC_SMTP_FROM_DISPLAY_NAME}
      - KC_SMTP_TLS=${KC_SMTP_TLS}
      - KC_SMTP_SSL=${KC_SMTP_SSL}
      - KC_SMTP_AUTH=${KC_SMTP_AUTH}
      - KC_SMTP_REPLY_TO=${KC_SMTP_REPLY_TO}
      - KC_SMTP_REPLY_TO_DISPLAY_NAME=${KC_SMTP_REPLY_TO_DISPLAY_NAME}
      - KC_LOGIN_THEME=${KC_LOGIN_THEME}
      - KC_EMAIL_THEME=${KC_EMAIL_THEME}
      - KC_ENABLE_VERIFY_EMAIL=${KC_ENABLE_VERIFY_EMAIL}
      - KC_ENABLE_RESET_PASSWORD=${KC_ENABLE_RESET_PASSWORD}

  keycloak:
    volumes:
      - ${DISTRO_PATH}/binaries/keycloak/themes:/opt/bitnami/keycloak/providers
