services: 
  nginx:
    image: nginx:1.27.4
    labels:
      traefik.enable: "true"
      traefik.http.routers.nginx.rule: "Host(`${O3_IFRAME_HOSTNAME}`)"
      traefik.http.routers.nginx.entrypoints: "websecure"
      traefik.http.services.nginx.loadbalancer.server.port: 80
    volumes:
      - ${O3_IFRAME_HTML_PATH}:/usr/share/nginx/html
    networks:
      - ozone
      - web
  env-substitution:
    image: mekomsolutions/env-substitution:0df956a
    environment:
      - SCHEME=${SCHEME}
      - O3_HOSTNAME=${O3_HOSTNAME}
